USE QLBH
GO
SELECT MASP, TENSP, A.MALOAI ,B.TENLOAI, SOLUONG, GIABAN, DVTINH, A.MANCC ,C.TENNCC, GHICHU, HINH, PTGIAMGIA, TIENGIAMGIA, TONGTIEN
FROM SANPHAM A
INNER JOIN LOAISANPHAM B ON A.MALOAI = B.MALOAI
INNER JOIN NHACUNGCAP C ON A.MANCC = C.MANCC

SELECT A.MAHDCT, A.MASP, B.TENSP, A.MALOAI, C.TENLOAI, A.GIABAN, A.SOLUONG, A.DVTINH, A.PTGIAMGIA, A.TIENGIAMGIA, A.TONGTIEN, MAHD FROM HOADONCT A INNER JOIN SANPHAM B ON A.MASP = B.MASP INNER JOIN LOAISANPHAM C ON A.MALOAI = C.MALOAI


SELECT MASP, TENSP,B.TENLOAI,SOLUONG,GIABAN,DVTINH,C.TENNCC,GHICHU,HINH 
FROM SANPHAM A
INNER JOIN LOAISANPHAM B ON A.MALOAI = B.MALOAI
INNER JOIN NHACUNGCAP C ON A.MANCC = C.MANCC
WHERE TENSP LIKE 'mi hao han'

SELECT MASP, TENSP,B.TENLOAI,SOLUONG,GIABAN,DVTINH,C.TENNCC,GHICHU,HINH 
FROM SANPHAM A
INNER JOIN LOAISANPHAM B ON A.MALOAI = B.MALOAI
INNER JOIN NHACUNGCAP C ON A.MANCC = C.MANCC

SELECT MALOAI FROM LOAISANPHAM WHERE TENLOAI like 'bia'

SELECT MAPNCT, B.MAPN, B.NGAYNHAP, B.MANCC, C.TENNCC, B.MANV, D.TENNV, A.MASP, E.TENSP, A.MALOAI, F.TENLOAI, DONGIANHAP,A.SOLUONG,A.DVTINH,A.TONGTIEN
FROM PHIEUNHAPCT A
INNER JOIN PHIEUNHAP B ON A.MAPN = B.MAPN
INNER JOIN NHACUNGCAP C ON B.MANCC = C.MANCC
INNER JOIN NHANVIEN D ON B.MANV = D.MANV
INNER JOIN SANPHAM E ON A.MASP = E.MASP
INNER JOIN LOAISANPHAM F ON E.MALOAI = F.MALOAI

SELECT A.MAHD ,A.MANV, C.TENNV, A.MAKH, D.TENKH, NGAYBAN,A.TONGTIEN 
FROM HOADON A 
INNER JOIN NHANVIEN C ON A.MANV = C.MANV 
INNER JOIN KHACHHANG D ON A.MAKH = D.MAKH
ORDER BY NGAYBAN DESC

DELETE FROM SANPHAM WHERE MASP = 'sp06'

SELECT TENLOAI FROM LOAISANPHAM WHERE TENLOAI like '%i%'

SELECT A.MAHD ,A.MANV, C.TENNV, A.MAKH, D.TENKH,A.TONGTIEN
FROM HOADON A 
INNER JOIN NHANVIEN C ON A.MANV = C.MANV
INNER JOIN KHACHHANG D ON A.MAKH = D.MAKH

SELECT A.MAHDCT, A.MASP, B.TENSP, A.MALOAI, C.TENLOAI, A.GIABAN, A.SOLUONG, A.DVTINH, A.PTGIAMGIA, A.TIENGIAMGIA, A.TONGTIEN, MAHD
FROM HOADONCT A
INNER JOIN SANPHAM B ON A.MASP = B.MASP
INNER JOIN LOAISANPHAM C ON A.MALOAI = C.MALOAI
WHERE MAHD LIKE 'hd02'

SELECT MALOAI, GIABAN, SOLUONG,DVTINH,PTGIAMGIA,TIENGIAMGIA,TONGTIEN FROM SANPHAM

SELECT MAHDCT FROM HOADONCT A INNER JOIN SANPHAM B ON A.MASP = B.MASP WHERE TENSP LIKE 'mi tien vua'

DELETE FROM HOADONCT WHERE MAHD LIKE '2022' 

SELECT SUM(TONGTIEN) AS TongGia FROM HOADONCT WHERE MAHD = 'hd01';

delete from HOADONCT where MAHD = '3'

SELECT A.SOLUONG FROM HOADONCT A INNER JOIN SANPHAM B ON A.MASP = B.MASP WHERE TENSP LIKE 'mi hao han'
SELECT COUNT(*) FROM HOADONCT A INNER JOIN SANPHAM B ON A.MASP = B.MASP WHERE TENSP LIKE 'mi hao han'
SELECT SUM(TONGTIEN) FROM HOADONCT WHERE MAHD like 'hd01'

SELECT C.TENSP,B.NGAYBAN,A.GIABAN,A.SOLUONG,A.PTGIAMGIA,A.TIENGIAMGIA,A.TONGTIEN FROM HOADONCT A INNER JOIN HOADON B ON A.MAHD = B.MAHD INNER JOIN SANPHAM C ON A.MASP = C.MASP ORDER BY B.NGAYBAN DESC

SELECT MASP,TENSP,A.MALOAI,B.TENLOAI,GIABAN,DVTINH,PTGIAMGIA,TIENGIAMGIA FROM SANPHAM A INNER JOIN LOAISANPHAM B ON A.MALOAI = B.MALOAI WHERE TENSP LIKE 'mi hao han'

CREATE PROC sp_soLuongBanRa
AS BEGIN
	SELECT 
		c.TENSP as tenSP,
		b.NGAYBAN as ngayBan,
		a.GIABAN as giaBan,
		a.SOLUONG as soLuong,
		a.PTGIAMGIA as ptGiamGia,
		a.TIENGIAMGIA as tienGiamGia,
		a.TONGTIEN as tongTien
		FROM HOADONCT A
		inner join HOADON B on a.MAHD = b.MAHD
		inner join SANPHAM C on a.MASP = c.MASP
		ORDER BY b.NGAYBAN Desc
   END
drop proc sp_soLuongBanRa

SELECT C.TENSP ,B.NGAYBAN,A.GIABAN,A.SOLUONG,A.PTGIAMGIA,A.TIENGIAMGIA,A.TONGTIEN 
FROM HOADONCT A
INNER JOIN HOADON B ON A.MAHD = B.MAHD 
INNER JOIN SANPHAM C ON A.MASP = C.MASP 
WHERE B.NGAYBAN >= '2023-01-03' AND B.NGAYBAN <= '2023-01-29'

select top 5 A.MASP, A.TENSP, SUM(C.TONGTIEN) as "TONGTIEN"
from SANPHAM A 
INNER JOIN HOADONCT B ON A.MASP = B.MASP
INNER JOIN HOADON C ON B.MAHD = C.MAHD
group by A.MASP, A.TENSP 
order by 'TONGTIEN' desc

SELECT MASP,TENSP, A.MALOAI,B.TENLOAI,GIABAN,SOLUONG,DVTINH,PTGIAMGIA,TIENGIAMGIA,TONGTIEN
FROM SANPHAM A 
INNER JOIN LOAISANPHAM B ON A.MALOAI = B.MALOAI 
WHERE TENSP LIKE 'mi hao han'

SELECT COUNT(TENSP) FROM HOADONCT A INNER JOIN SANPHAM B ON A.MASP = B.MASP WHERE MAHD LIKE '2071'

SELECT B.MAHD 
FROM HOADON A
INNER JOIN HOADONCT B ON A.MAHD = B.MAHD 
INNER JOIN SANPHAM C ON B.MASP = C.MASP
WHERE C.TENSP LIKE 'mi hao han'

SELECT *, PARSENAME(REPLACE(TENKH, ' ', '.'), 1) AS TenCuoiCung FROM KHACHHANG ORDER BY TenCuoiCung ASC

SELECT MALOAI FROM LOAISANPHAM WHERE TENLOAI like N'sữa'

SELECT MASP, TENSP, B.TENLOAI, D.TENDVT, SOLUONG, GIABAN, GIANHAP, TENDVT, TENNCC, HINH, PTGIAMGIA, TIENGIAM, GHICHU
FROM SANPHAM A
INNER JOIN LOAISANPHAM B ON A.MALOAI = B.MALOAI
INNER JOIN NHACUNGCAP C ON A.MANCC = C.MANCC
INNER JOIN DVT D ON A.MADVT = D.MADVT

SELECT A.*, TENLOAI, TENNCC, TENDVT
FROM SANPHAM A
INNER JOIN LOAISANPHAM B ON A.MALOAI = B.MALOAI
INNER JOIN NHACUNGCAP C ON A.MANCC = C.MANCC
INNER JOIN DVT D ON A.MADVT = D.MADVT

SELECT *, C.TENLOAI, D.TENDVT
FROM HOADONCT A 
INNER JOIN SANPHAM B ON A.MASP = B.MASP 
INNER JOIN LOAISANPHAM C ON A.MALOAI = C.MALOAI 
INNER JOIN DVT D ON A.MADVT = D.MADVT

SELECT SUM(THANHTIEN) FROM HOADONCT WHERE MAHD like 'HD001'

SELECT TENKH FROM KHACHHANG WHERE TENKH LIKE N'%Đỗ%'

SELECT MAKH + TENKH + SDT FROM KHACHHANG