CREATE DATABASE QLBH
GO 
USE QLBH
GO
CREATE TABLE NHANVIEN(
MANV CHAR(10) PRIMARY KEY,
TENNV NVARCHAR(100) NOT NULL,
SDT NVARCHAR(15) NOT NULL,
EMAIL NVARCHAR(50) NOT NULL,
MATKHAU NVARCHAR(255) NOT NULL,
DIACHI NVARCHAR(255) NOT NULL,
NGAYSINH DATE NOT NULL,
GIOITINH BIT NOT NULL,
VAITRO BIT NOT NULL,
HINH NVARCHAR(50) NOT NULL
)
GO
CREATE TABLE KHACHHANG(
MAKH CHAR(10) PRIMARY KEY,
TENKH NVARCHAR(100) NOT NULL,
SDT NVARCHAR(15) NOT NULL,
GHICHU NVARCHAR(255)
)
GO 
CREATE TABLE NHACUNGCAP(
MANCC CHAR(10) PRIMARY KEY,
TENNCC NVARCHAR(100) NOT NULL,
DIACHI NVARCHAR(255) NOT NULL ,
SDT NVARCHAR(15) NOT NULL,
EMAIL NVARCHAR(50) NOT NULL
)
GO
CREATE TABLE LOAISANPHAM(
MALOAI CHAR(10) PRIMARY KEY,
TENLOAI NVARCHAR(100) NOT NULL
)
GO
CREATE TABLE DVT(
MADVT CHAR(10) PRIMARY KEY,
TENDVT NVARCHAR(100) NOT NULL,
)
GO
CREATE TABLE SANPHAM(
MASP CHAR(10) PRIMARY KEY,
TENSP NVARCHAR(100) NOT NULL,
MALOAI CHAR(10),
SOLUONG INT NOT NULL,
GIABAN FLOAT NOT NULL,
GIANHAP FLOAT NOT NULL,
MADVT CHAR(10),
MANCC CHAR(10),
HINH NVARCHAR(255) NOT NULL,
PTGIAMGIA FLOAT,
TIENGIAM FLOAT,
GHICHU NVARCHAR(255),
FOREIGN KEY (MALOAI) REFERENCES LOAISANPHAM(MALOAI),
FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC),
FOREIGN KEY (MADVT) REFERENCES DVT(MADVT)
)
GO
CREATE TABLE PHIEUNHAP(
MAPN CHAR(10) PRIMARY KEY,
NGAYNHAP DATE DEFAULT GETDATE(),
MANCC CHAR(10),
MANV CHAR(10),
FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC),
FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
)
GO
CREATE TABLE PHIEUNHAPCT(
MAPNCT CHAR(10) PRIMARY KEY,
MAPN CHAR(10),
MASP CHAR(10),
MALOAI CHAR(10),
GIANHAP FLOAT NOT NULL,
SOLUONG INT NOT NULL,
MADVT CHAR(10),
THANHTIEN FLOAT,
FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP),
FOREIGN KEY (MAPN) REFERENCES PHIEUNHAP(MAPN),
FOREIGN KEY (MALOAI) REFERENCES LOAISANPHAM(MALOAI),
FOREIGN KEY (MADVT) REFERENCES DVT(MADVT)
)
GO
CREATE TABLE HOADON(
MAHD CHAR(10) PRIMARY KEY,
MANV CHAR(10),
MAKH CHAR(10),
NGAYBAN DATE DEFAULT GETDATE(),
THANHTIEN FLOAT,
FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
)
GO
CREATE TABLE HOADONCT(
MAHDCT CHAR(10) PRIMARY KEY,
MASP CHAR(10),
MALOAI CHAR(10),
GIABAN FLOAT NOT NULL,
SOLUONG INT NOT NULL,
MADVT CHAR(10),
PTGIAMGIA FLOAT NOT NULL,
THANHTIEN FLOAT,
MAHD CHAR(10),
FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP),
FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
FOREIGN KEY (MALOAI) REFERENCES LOAISANPHAM(MALOAI),
FOREIGN KEY (MADVT) REFERENCES DVT(MADVT)
)

