/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.edusys.ui;

import com.edusys.dao.NhanVienDAO;
import com.edusys.utils.Auth;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author cutr0
 */
public class pnDoiMatKhau extends javax.swing.JPanel {

    boolean hienMK1 = true;
    boolean hienMK2 = true;
    boolean hienMK3 = true;
    NhanVienDAO dao = new NhanVienDAO();

    /**
     * Creates new form pnDoiMatKhau
     */
    public pnDoiMatKhau() {
        initComponents();
    }

    private void doiMatKhau() {
        String matKhau = new String(txtMatKhau1.getPassword());
        String matKhauMoi = new String(txtMatKhau2.getPassword());
        String matKhauMoi2 = new String(txtMatKhau3.getPassword());

        if (!matKhau.equals(Auth.user.getMatKhau())) {
            JOptionPane.showMessageDialog(this, "Sai mật khẩu");
        } else if (matKhau.equalsIgnoreCase(matKhauMoi)) {
            JOptionPane.showMessageDialog(this, "Mật khẩu mới không được trùng với mật khẩu cũ");
        } else if (!matKhauMoi.equals(matKhauMoi2)) {
            JOptionPane.showMessageDialog(this, "Xác nhận mật khẩu không đúng!");
        } else {
            try {
                Auth.user.setMatKhau(matKhauMoi);
                dao.update(Auth.user);
                JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công!");
                new DangNhap().setVisible(true);
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Đổi mật khẩu không thành công!");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnKhungDangNhap = new javax.swing.JPanel();
        lblHienMk1 = new javax.swing.JLabel();
        lblHienMk2 = new javax.swing.JLabel();
        lblHienMk3 = new javax.swing.JLabel();
        lblDangNhap = new javax.swing.JLabel();
        lblTenDangNhap = new javax.swing.JLabel();
        lblMatKhau = new javax.swing.JLabel();
        btnDangNhap = new javax.swing.JButton();
        txtMatKhau2 = new javax.swing.JPasswordField();
        txtMatKhau1 = new javax.swing.JPasswordField();
        lblNhapLai = new javax.swing.JLabel();
        txtMatKhau3 = new javax.swing.JPasswordField();
        lblBackHome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1620, 1080));
        setMinimumSize(new java.awt.Dimension(1620, 1080));
        setPreferredSize(new java.awt.Dimension(1620, 1080));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnKhungDangNhap.setBackground(new java.awt.Color(255, 255, 255));
        pnKhungDangNhap.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHienMk1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/icons8-closed-eye-24.png"))); // NOI18N
        lblHienMk1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHienMk1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHienMk1MouseClicked(evt);
            }
        });
        pnKhungDangNhap.add(lblHienMk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, -1));

        lblHienMk2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/icons8-closed-eye-24.png"))); // NOI18N
        lblHienMk2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHienMk2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHienMk2MouseClicked(evt);
            }
        });
        pnKhungDangNhap.add(lblHienMk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, -1, -1));

        lblHienMk3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/icons8-closed-eye-24.png"))); // NOI18N
        lblHienMk3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHienMk3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHienMk3MouseClicked(evt);
            }
        });
        pnKhungDangNhap.add(lblHienMk3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, -1, -1));

        lblDangNhap.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblDangNhap.setText("ĐỔI MẬT KHẨU");
        lblDangNhap.setPreferredSize(new java.awt.Dimension(300, 64));
        pnKhungDangNhap.add(lblDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 270, -1));

        lblTenDangNhap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTenDangNhap.setText("Mật khẩu hiện tại");
        pnKhungDangNhap.add(lblTenDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        lblMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMatKhau.setText("Mật khẩu mới");
        pnKhungDangNhap.add(lblMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, -1));

        btnDangNhap.setBackground(new java.awt.Color(106, 139, 255));
        btnDangNhap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnDangNhap.setText("Xác nhận đổi");
        btnDangNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDangNhapMouseClicked(evt);
            }
        });
        pnKhungDangNhap.add(btnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 300, 40));
        pnKhungDangNhap.add(txtMatKhau2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 300, 40));
        pnKhungDangNhap.add(txtMatKhau1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 300, 40));

        lblNhapLai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNhapLai.setText("Nhập lại mật khẩu mới");
        pnKhungDangNhap.add(lblNhapLai, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));
        pnKhungDangNhap.add(txtMatKhau3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 300, 40));

        lblBackHome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBackHome.setText("Quay lại trang chủ");
        lblBackHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBackHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackHomeMouseClicked(evt);
            }
        });
        pnKhungDangNhap.add(lblBackHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, -1, -1));

        add(pnKhungDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 680, 1040));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/hinhnen2.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1620, 1080));
    }// </editor-fold>//GEN-END:initComponents

    private void lblHienMk1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHienMk1MouseClicked
        if (hienMK1 == true) {
            txtMatKhau1.setEchoChar((char) 0);
            lblHienMk1.setIcon(new ImageIcon("D:\\DuAn1NetBean\\DuAn1\\src\\com\\edusys\\icons\\icons8-eye-24 (1).png"));
            hienMK1 = false;
        } else if (hienMK1 == false) {
            txtMatKhau1.setEchoChar('*');
            lblHienMk1.setIcon(new ImageIcon("D:\\DuAn1NetBean\\DuAn1\\src\\com\\edusys\\icons\\icons8-closed-eye-24.png"));
            hienMK1 = true;
        }
    }//GEN-LAST:event_lblHienMk1MouseClicked

    private void lblHienMk3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHienMk3MouseClicked
        if (hienMK3 == true) {
            txtMatKhau3.setEchoChar((char) 0);
            lblHienMk3.setIcon(new ImageIcon("D:\\DuAn1NetBean\\DuAn1\\src\\com\\edusys\\icons\\icons8-eye-24 (1).png"));
            hienMK3 = false;
        } else if (hienMK3 == false) {
            txtMatKhau3.setEchoChar('*');
            lblHienMk3.setIcon(new ImageIcon("D:\\DuAn1NetBean\\DuAn1\\src\\com\\edusys\\icons\\icons8-closed-eye-24.png"));
            hienMK3 = true;
        }
    }//GEN-LAST:event_lblHienMk3MouseClicked

    private void lblHienMk2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHienMk2MouseClicked
        if (hienMK2 == true) {
            txtMatKhau2.setEchoChar((char) 0);
            lblHienMk2.setIcon(new ImageIcon("D:\\DuAn1NetBean\\DuAn1\\src\\com\\edusys\\icons\\icons8-eye-24 (1).png"));
            hienMK2 = false;
        } else if (hienMK2 == false) {
            txtMatKhau2.setEchoChar('*');
            lblHienMk2.setIcon(new ImageIcon("D:\\DuAn1NetBean\\DuAn1\\src\\com\\edusys\\icons\\icons8-closed-eye-24.png"));
            hienMK2 = true;
        }
    }//GEN-LAST:event_lblHienMk2MouseClicked

    private void btnDangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangNhapMouseClicked
        doiMatKhau();
    }//GEN-LAST:event_btnDangNhapMouseClicked

    private void lblBackHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackHomeMouseClicked
        new TrangChu().setVisible(true);
    }//GEN-LAST:event_lblBackHomeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBackHome;
    private javax.swing.JLabel lblDangNhap;
    private javax.swing.JLabel lblHienMk1;
    private javax.swing.JLabel lblHienMk2;
    private javax.swing.JLabel lblHienMk3;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JLabel lblNhapLai;
    private javax.swing.JLabel lblTenDangNhap;
    private javax.swing.JPanel pnKhungDangNhap;
    private javax.swing.JPasswordField txtMatKhau1;
    private javax.swing.JPasswordField txtMatKhau2;
    private javax.swing.JPasswordField txtMatKhau3;
    // End of variables declaration//GEN-END:variables
}
