/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.edusys.ui;

import com.edusys.utils.JdbcHelper;
import java.awt.Color;
import java.sql.ResultSet;

/**
 *
 * @author cutr0
 */
public class pnTrangChu extends javax.swing.JPanel {

    /**
     * Creates new form pnTrangChu
     */
    public pnTrangChu() {
        initComponents();
        hienThiSoLuong();
    }

    void hienThiSoLuong() {
        String sql1 = "SELECT COUNT(*) FROM NHANVIEN";
        String sql2 = "SELECT COUNT(*) FROM KHACHHANG";
        String sql3 = "SELECT COUNT(*) FROM SANPHAM";
        try {
            ResultSet rs = JdbcHelper.query(sql1);
            while (rs.next()) {
                lblSLNV.setText(rs.getString(1));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        try {
            ResultSet rs = JdbcHelper.query(sql2);
            while (rs.next()) {
                lblSLKH.setText(rs.getString(1));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        try {
            ResultSet rs = JdbcHelper.query(sql3);
            while (rs.next()) {
                lblSLSP.setText(rs.getString(1));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblSLNV = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblSLSP = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        lblSLKH = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1620, 1080));
        setMinimumSize(new java.awt.Dimension(1620, 1080));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(106, 139, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SỐ LƯỢNG NHÂN VIÊN");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/icons8-user-account-96.png"))); // NOI18N
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        lblSLNV.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSLNV.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(lblSLNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 30));

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 400, 120));

        jPanel6.setBackground(new java.awt.Color(106, 139, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("SỐ LƯỢNG MẶT HÀNG");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/icons8-parcel-96.png"))); // NOI18N
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        lblSLSP.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSLSP.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.add(lblSLSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 30));

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 30, 400, 120));

        jPanel7.setBackground(new java.awt.Color(106, 139, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("SỐ LƯỢNG KHÁCH HÀNG");
        jPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/icons8-user-96.png"))); // NOI18N
        jPanel7.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        lblSLKH.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSLKH.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.add(lblSLKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 30));

        add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 400, 120));

        jPanel9.setBackground(new java.awt.Color(106, 139, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("QUẢN LÝ SẢN PHẨM");
        jPanel9.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/icons8-parcel-96.png"))); // NOI18N
        jPanel9.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 400, 120));

        jPanel8.setBackground(new java.awt.Color(106, 139, 255));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("QUẢN LÝ NHÂN VIÊN");
        jPanel8.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/icons8-user-account-96.png"))); // NOI18N
        jPanel8.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 400, 120));

        jPanel10.setBackground(new java.awt.Color(106, 139, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("QUẢN LÝ HÓA ĐƠN");
        jPanel10.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/icons8-list-96.png"))); // NOI18N
        jPanel10.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 200, 400, 120));

        jPanel12.setBackground(new java.awt.Color(106, 139, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên sản phẩm", "Tên loại", "Số lượng"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        jPanel12.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 740, 530));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên sản phẩm", "Tên loại", "Số lượng"
            }
        ));
        jScrollPane5.setViewportView(jTable2);

        jPanel12.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 50, 740, 530));

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("MẶT HÀNG NHẬP NHIỀU NHẤT");
        jPanel12.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, -1, -1));

        jLabel38.setBackground(new java.awt.Color(255, 255, 255));
        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("MẶT HÀNG BÁN CHẠY NHẤT");
        jPanel12.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 1560, 610));
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked

    }//GEN-LAST:event_jPanel8MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblSLKH;
    private javax.swing.JLabel lblSLNV;
    private javax.swing.JLabel lblSLSP;
    // End of variables declaration//GEN-END:variables
}
