CREATE DATABASE QLBH
GO 
USE QLBH
GO
CREATE TABLE NHANVIEN(
MANV CHAR(10) PRIMARY KEY,
TENNV NVARCHAR(30) NOT NULL,
SDT NVARCHAR(15) NOT NULL,
EMAIL NVARCHAR(50) NOT NULL,
MATKHAU NVARCHAR(255) NOT NULL,
DIACHI NVARCHAR(255) NOT NULL,
GIOITINH BIT NOT NULL,
VAITRO BIT NOT NULL,
HINH NVARCHAR(50) NOT NULL,
)
GO
CREATE TABLE KHACHHANG(
MAKH CHAR(10) PRIMARY KEY,
TENKH NVARCHAR(30) NOT NULL,
SDT NVARCHAR(15) NOT NULL,
DIACHI NVARCHAR(255),
GHICHU NVARCHAR(255)
)
GO 
CREATE TABLE NHACUNGCAP(
MANCC CHAR(10) PRIMARY KEY,
TENNCC NVARCHAR(30) NOT NULL,
DIACHI NVARCHAR(255) NOT NULL ,
SDT NVARCHAR(15) NOT NULL,
EMAIL NVARCHAR(50) NOT NULL

)
GO
CREATE TABLE LOAISANPHAM(
MALOAI CHAR(10) PRIMARY KEY,
TENLOAI NVARCHAR(30) NOT NULL,
)
GO
CREATE TABLE SANPHAM(
MASP CHAR(10) PRIMARY KEY,
TENSP NVARCHAR(30) NOT NULL,
MALOAI CHAR(10),
SOLUONG INT NOT NULL,
GIABAN FLOAT NOT NULL,
DVTINH NVARCHAR(15) NOT NULL,
MANCC CHAR(10),
GHICHU NVARCHAR(255) NOT NULL,
HINH NVARCHAR(255) NOT NULL,
FOREIGN KEY (MALOAI) REFERENCES LOAISANPHAM(MALOAI),
FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC),
)
GO
CREATE TABLE PHIEUNHAP(
MAPN CHAR(10) PRIMARY KEY,
NGAYNHAP DATE NOT NULL,
TONGSOLUONG INT NOT NULL,
TONGTIEN FLOAT NOT NULL,
MANCC CHAR(10),
MANV CHAR(10),
FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC),
FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
)
GO
CREATE TABLE PHIEUNHAPCT(
MAPNCT CHAR(10) PRIMARY KEY,
MAPN CHAR(10),
MASP CHAR(10),
TENSP NVARCHAR(255),
MALOAI CHAR(10),
DONGIANHAP FLOAT,
THANHTIEN FLOAT,
SOLUONG INT,
FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP),
FOREIGN KEY (MAPN) REFERENCES PHIEUNHAP(MAPN),
FOREIGN KEY (MALOAI) REFERENCES LOAISANPHAM(MALOAI)
)
GO
CREATE TABLE HOADON(
MAHD CHAR(10) PRIMARY KEY,
MANV CHAR(10),
TENNV NVARCHAR(30) NOT NULL,
MAKH CHAR(10),
TENKH NVARCHAR(30) NOT NULL,
TONGTIEN FLOAT,
DONGIABAN FLOAT,
PTGIAMGIA FLOAT,
TIENGIAMGIA FLOAT,
FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
)
GO
CREATE TABLE HOADONCT(
MAHDCT CHAR(10) PRIMARY KEY,
MASP CHAR(10),
TENSP NVARCHAR(30) NOT NULL,
MALOAI CHAR(10),
SOLUONG INT,
MAHD CHAR(10),
FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP),
FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
FOREIGN KEY (MALOAI) REFERENCES LOAISANPHAM(MALOAI)
)

INSERT INTO NHANVIEN(MANV,TENNV,SDT,EMAIL,MATKHAU,DIACHI,GIOITINH,VAITRO,HINH) values 
('nv01','Vo Khanh Toan','076389837','toanvkpc05433@fpt.edu.vn','123','Can Tho',1,1,'avt1.jpg'),
('nv02','Phan Minh Sang','084377234','sangpmpc05409@fpt.edu.vn','123','Binh Duong',1,0,'avt2.jpg')
GO
INSERT INTO KHACHHANG(MAKH,TENKH, SDT,DIACHI,GHICHU) values 
('kh01','Ha  Thanh Nhe','02174832835','Binh Duong','Khach Quen'),
('kh02','Tran Quoc Thinh','02174832835','Ha Tien','Khach Quen')
GO
INSERT INTO NHACUNGCAP(MANCC,TENNCC, DIACHI,SDT,EMAIL) values 
('mancc01','ace cook','binh duong','0123456789','acecook@gmail.com')
GO
INSERT INTO NHACUNGCAP(MANCC,TENNCC, DIACHI,SDT,EMAIL) values 
('mancc02','masan','da nang','0123456789','masan@gmail.com')
GO
INSERT INTO NHACUNGCAP(MANCC,TENNCC, DIACHI,SDT,EMAIL) values 
('mancc03','heineken','da nang','0123456789','heineken@gmail.com')
GO
INSERT INTO LOAISANPHAM(MALOAI,TENLOAI) values 
('ml01','mi')
GO
INSERT INTO LOAISANPHAM(MALOAI,TENLOAI) values 
('ml02','bia')
GO
INSERT INTO SANPHAM(MASP,TENSP, MALOAI,SOLUONG,GIABAN,DVTINH,MANCC,GHICHU,HINH) values 
('sp01','mi hao han','ml01','1','3500','thung','mancc01','ban chay','mihaohao.png')
GO
INSERT INTO SANPHAM(MASP,TENSP, MALOAI,SOLUONG,GIABAN,DVTINH,MANCC,GHICHU,HINH) values 
('sp02','mi doraemon','ml01','1','3600','thung','mancc01','ban chay','midoraemon.png')
GO
INSERT INTO SANPHAM(MASP,TENSP, MALOAI,SOLUONG,GIABAN,DVTINH,MANCC,GHICHU,HINH) values 
('sp03','mi tien vua','ml01','1','3400','thung','mancc02','ban chay','mitienvua.png')
GO
INSERT INTO SANPHAM(MASP,TENSP, MALOAI,SOLUONG,GIABAN,DVTINH,MANCC,GHICHU,HINH) values 
('sp04','bia tiger','ml02','1','18000','long','mancc02','ban chay','biatiger.png')
GO

SELECT MASP, TENSP, A.MALOAI ,B.TENLOAI, SOLUONG, GIABAN, DVTINH, A.MANCC ,C.TENNCC, GHICHU, HINH 
FROM SANPHAM A
INNER JOIN LOAISANPHAM B ON A.MALOAI = B.MALOAI
INNER JOIN NHACUNGCAP C ON A.MANCC = C.MANCC

SELECT MASP, TENSP,B.TENLOAI,SOLUONG,GIABAN,DVTINH,C.TENNCC,GHICHU,HINH 
FROM SANPHAM A
INNER JOIN LOAISANPHAM B ON A.MALOAI = B.MALOAI
INNER JOIN NHACUNGCAP C ON A.MANCC = C.MANCC
WHERE TENSP LIKE 'mi hao han'

SELECT MASP, TENSP,B.TENLOAI,SOLUONG,GIABAN,DVTINH,C.TENNCC,GHICHU,HINH 
FROM SANPHAM A
INNER JOIN LOAISANPHAM B ON A.MALOAI = B.MALOAI
INNER JOIN NHACUNGCAP C ON A.MANCC = C.MANCC
WHERE GIABAN > 3500